alias er='mate .'
alias rdbm='rake db:migrate'
alias devlog='tail -f log/development.log'
alias testlog='tail -f log/test.log'
alias rp='mkdir -p tmp; touch tmp/restart.txt'
alias rdbs='rake db:seed'
alias be='bundle exec'
